---
- hosts: all
  tasks:
    - include_vars:
        file: ansible_variables.yml
        name: variable

    - file:
        path: /home/{{ variable.user }}/code
        state: directory
        mode: "0755"

    - git:
        repo: "https://otokki2100@github.com/otokki2100/{{ item }}.git"
        dest: /home/{{ variable.user }}/code/{{ item }}
      with_items:
        - cloud-aws
        - svc-iac
        - svc-web
        - svc-conn
        - svc-repo
        - lang-code

    - ansible.builtin.shell:
        cmd: sh ~/code/lang-code/shell/init/init-{{ variable.dist }}.sh {{ variable.user }} {{ variable.dist }} {{ variable.domain }}
