---
- hosts: all
  tasks:
    - include_vars:
        file: ansible_variables.yml
        name: variable

    - file:
        path: /home/{{ variable.user }}/code
        state: directory
        mode: "0755"

    - git:
        repo: "https://otokki2100@github.com/otokki2100/{{ item }}"
        dest: /home/{{ variable.user }}/code/{{ item }}
      with_items:
        - cloud-aws.git
        - svc-iac.git
        - svc-web.git
        - svc-conn.git
        - svc-repo.git
        - lang-code.git

    - ansible.builtin.shell:
        cmd: sh ~/code/lang-code/shell/init/init-{{ variable.domain }}.sh
